### ISSUE TITLE
Drupal.org documentation heads up

### ISSUE THREAD

**Issue by kaaresl** [arnested/drupal-mode#51]
I've recently rewritten the book pages about Emacs on drupal.org, and provided an example installation using this mode. It is currently in need of technical overview and it would be helpful if you could take a look at it.

https://www.drupal.org/node/2327741

The overall idea of the [Emacs] section is to document each take on Drupal modes individually and for this particular solution I've chosen to provide an example installation that utilizes many cool parts of it, rather than document every aspect of it.

[emacs]: https://www.drupal.org/node/2327299

**Comment by arnested** [comment]
I reviewed your changes (again) and still find them good. Closing this issue. Thanks, @kaaresl.
