### ISSUE TITLE
drupal-phpcs generates error with flycheck 'release-0.22'

### ISSUE THREAD

**Issue by dhaley** [arnested/drupal-mode#56]
I upgraded to flycheck 'release-0.22', which broke the 'drupal-phpcs' checker.

(flycheck-select-checker 'drupal-phpcs)

generates this error:

Can't use syntax checker drupal-phpcs in this buffer

**Comment by xendk** [comment]
You're not supposed to select the checker specifically, flycheck will automatically use the first compatible checker, and the drupal-phpcs makes an effort of adding itself as next-checker to all checker that'll run in any major-mode that drupal-mode supports.

The notable exception being, funnily enough, php-mode itself, as we just set the phpcs standard to the Drupal Coding Standard and use the regular phpcs cheker.

The drupal-phpcs checker is an oddity, as it's running phpcs on *non-php* files, as the regular phpcs checker only runs in php modes. 

What kind of file are you trying to check?

**Comment by dhaley** [comment]
I'm just trying to check a Drupal .module file.

Phpcs works at the command line:

phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme sws.module 

...And flycheck-verify-setup looks fine.

Syntax checkers for buffer sws_fg.module in php-mode:

  php
    - predicate:  t
    - executable: Found at /Applications/MAMP/bin/php/php5.5.18/bin/php

  php-phpmd
    - predicate:  t
    - executable: Found at /Users/dhaley/.composer/vendor/bin/phpmd

  php-phpcs
    - predicate:  t
    - executable: Found at /Users/dhaley/.composer/vendor/bin/phpcs

Flycheck Mode is enabled.

But flycheck-next-error, generates "No more Flycheck errors," which I know isn't true.  Any idea, how I could troubleshoot further?

**Comment by xendk** [comment]
Is drupal-mode active? 

What's the value of the flycheck-phpcs-standard variable?

**Comment by dhaley** [comment]
It looks like this is not an issue with drupal-mode as I can't get the php-phpcs checker to apply to non-Drupal php buffers.

I have opened an issue with flycheck (https://github.com/flycheck/flycheck/issues/561) as I can't get the php-phpcs checker to apply on a php buffer even using Emacs -Q to rule out my configuration settings.

Let me know if you have any other suggestions though.

**Comment by dhaley** [comment]
This is not an issue with drupal-mode, but I did learn a lot about drupal phpcs checker :+1:   Closing.
