### ISSUE TITLE
Async cache clear

### ISSUE THREAD

**Issue by kostajh** [arnested/drupal-mode#60]
Hi @arnested,

how do you feel  about using `async-shell-command` for `drupal-drush-cache-clear ()` instead of `call-process`? On some sites I work on, clearing the cache can take upwards of a minute, which is a long time for Emacs to be locked up.

Kosta

**Comment by arnested** [comment]
I like it. And I might even have some half finished code for it somewhere.

Will look into it later today or tomorrow.

**Comment by arnested** [comment]
I implemented something now.

The cache clear is run in the background (asynchronous).

If you have [async.el](https://github.com/jwiegley/emacs-async) installed you will even get feedback when til cache clearing is done.

**Comment by kostajh** [comment]
great, thank you!
