### ISSUE TITLE
symbol's value as variable is void: gtags-auto-update

### ISSUE THREAD

**Issue by bmag** [arnested/drupal-mode#61]
Looks like a recent [commit](https://github.com/arnested/drupal-mode/commit/73a1531435699ef2bcc879fa27031d3b513a7215) introduced a bug.
`gtags-auto-update` is being accessed when it isn't defined, causing an error: "symbol's value as variable is void: gtags-auto-update".

Backtrace:
```
Debugger entered--Lisp error: (void-variable gtags-auto-update)
  (if (boundp (quote gtags-auto-update)) nil gtags-auto-update)
  (unless (boundp (quote gtags-auto-update)) gtags-auto-update)
  (and (unless (boundp (quote gtags-auto-update)) gtags-auto-update) drupal-drush-program (zerop (call-process drupal-drush-program nil nil nil "help" "etags")))
  eval((and (unless (boundp (quote gtags-auto-update)) gtags-auto-update) drupal-drush-program (zerop (call-process drupal-drush-program nil nil nil "help" "etags"))))
  byte-code("\303\304N\211\203
```

Original issue reported in Spacemacs: https://github.com/syl20bnr/spacemacs/issues/2153

**Comment by arnested** [comment]
I should not be no less not caring when doing double negations or something.

Thanks for the report.

Will do an official release right away.
