### ISSUE TITLE
Drupal mode stoped working

### ISSUE THREAD

**Issue by jsobiecki** [arnested/drupal-mode#74]
Hello,

After one of update packages, drupal-mode stopped working. Possible source of problem - when I try to trigger drupal-mode manually, I got "_flycheck-define-generic-checker: Missing :modes in syntax checker drupal-phpcs_".

**Comment by xendk** [comment]
Hello,

What version of flycheck are you running?

**Comment by jsobiecki** [comment]
> Flycheck version: 30snapshot (package: 20160912.814)

**Comment by xendk** [comment]
Should be fixed in HEAD now.

Will need to be reworked again when they finish the new checker selection system.

**Comment by jsobiecki** [comment]
@xendk - thanks! I'll check and let you know if it fix problem for me :)

**Comment by kostajh** [comment]
Working for me. Thanks @xendk!

**Comment by jsobiecki** [comment]
It works for me also, thanks guys! I'm closing this issue.
