### ISSUE TITLE
drupal-mode-beginning-of-line obsoleted?

### ISSUE THREAD

**Issue by xendk** [arnested/drupal-mode#79]
`drupal-mode-beginning-of-line` doesn't play ball with auto-indent-mode. auto-indent-mode adds an advice on `move-beginning-of-line` that makes C-a toggle between beginning of line and beginning of indentation.

`drupal-mode-beginning-of-line` uses `beginning-of-line` which isn't adviced.

Seems that most other modes uses `move-beginning-of-line`.

I think that either should `drupal-mode-beginning-of-line` be made to use `move-beginning-of-line`, or it should be dropped (not much future in the conf-mode anyway).

**Comment by arnested** [comment]
Let's just drop it.

**Comment by xendk** [comment]
OK, I'll kill it...

**Comment by xendk** [comment]
Closed in https://github.com/arnested/drupal-mode/commit/6f40ad04b760d2266b8c07283df266471d85a9b2
